# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14speech_service.proto\x12\x06speech\"\x1e\n\rSpeechRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0eSpeechResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2U\n\rSpeechService\x12\x44\n\x13\x45xecuteConversation\x12\x15.speech.SpeechRequest\x1a\x16.speech.SpeechResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHREQUEST']._serialized_start=32
  _globals['_SPEECHREQUEST']._serialized_end=62
  _globals['_SPEECHRESPONSE']._serialized_start=64
  _globals['_SPEECHRESPONSE']._serialized_end=94
  _globals['_SPEECHSERVICE']._serialized_start=96
  _globals['_SPEECHSERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
